#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 3 "..\..\Mail\Templates\CreatedAccount.cshtml"
    using Hipicapp.Service.Mail.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class _Mail_Templates_CreatedAccount_cshtml : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 5 "..\..\Mail\Templates\CreatedAccount.cshtml"

    public CreatedAccountEmailModel message;

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n\r\n");


WriteLiteral("\r\n");


WriteLiteral("\r\n\r\n<html>\r\n<head>\r\n    <title>Nuevo registro | Hipicapp</title>\r\n</head>\r\n<body>" +
"\r\n    <p>Bienvenido a Hipicapp! Puede acceder a su cuenta en <a target=\"_blank\" " +
"href=\"");


            
            #line 14 "..\..\Mail\Templates\CreatedAccount.cshtml"
                                                                               Write(message.Url);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 14 "..\..\Mail\Templates\CreatedAccount.cshtml"
                                                                                             Write(message.Url);

            
            #line default
            #line hidden
WriteLiteral("</a>.</p>\r\n    <p>Gracias,</p>\r\n    <p>El equipo de cuentas de Hipicapp</p>\r\n</bo" +
"dy>\r\n</html>");


        }
    }
}
#pragma warning restore 1591
