#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 3 "..\..\Mail\Templates\PasswordReset.cshtml"
    using Hipicapp.Service.Mail.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class _Mail_Templates_PasswordReset_cshtml : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 5 "..\..\Mail\Templates\PasswordReset.cshtml"

    public PasswordResetEmailModel message;

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n\r\n");


WriteLiteral("\r\n");


WriteLiteral(@"

<html>
<head>
    <title>Welcome to mysite.com</title>
</head>
<body>
    <p>Dear ,</p>
    <p>An account has been created for you.</p>
    <p>Your account is FREE and allows you to perform bla bla features.</p>
    <p>To login and complete your profile, please go to:</p>
    <p><a href=""");


            
            #line 18 "..\..\Mail\Templates\PasswordReset.cshtml"
           Write(message.Url);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 18 "..\..\Mail\Templates\PasswordReset.cshtml"
                         Write(message.Url);

            
            #line default
            #line hidden
WriteLiteral("</a></p>\r\n</body>\r\n</html>");


        }
    }
}
#pragma warning restore 1591
