#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 4 "..\..\Templates\AdvanceProgram.cshtml"
    using Hipicapp.Model.Event;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Templates\AdvanceProgram.cshtml"
    using Hipicapp.Model.Participant;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class _Templates_AdvanceProgram_cshtml : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 6 "..\..\Templates\AdvanceProgram.cshtml"

    public Competition competition;
    public IList<Enrollment> inscriptions;
    public IList<Seminary> seminary;

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n\r\n");



WriteLiteral("\r\n");


WriteLiteral(@"

<!DOCTYPE html>
<html>
<head>
    <title>Contenido del concurso</title>
</head>
<body>
    <h2>Datos generales del concurso</h2>
    <hr style=""margin:0 0 15px; height: 3px; color:#f74b4b; background:#f74b4b;"" />
    <table border=""0"">
        <tbody>
            <tr>
                <td>                    
                    <h3> ");


            
            #line 24 "..\..\Templates\AdvanceProgram.cshtml"
                    Write(competition.Name);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n                </td>\r\n            </tr>\r\n            <tr>                " +
"\r\n                <td>\r\n                    <p style=\"margin-bottom:10px;\"><stro" +
"ng>Categoría:</strong> ");


            
            #line 29 "..\..\Templates\AdvanceProgram.cshtml"
                                                                          Write(competition.Category.Name);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n               " +
" <td>\r\n                    <p style=\"margin-bottom:10px;\"><strong>Recinto:</stro" +
"ng> ");


            
            #line 34 "..\..\Templates\AdvanceProgram.cshtml"
                                                                        Write(competition.Address);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                </td>\r\n            </tr>\r\n            <tr>             \r\n  " +
"              <td>\r\n                    <p style=\"margin-bottom:10px;\"><strong>D" +
"isciplina:</strong> ");


            
            #line 39 "..\..\Templates\AdvanceProgram.cshtml"
                                                                           Write(competition.Specialty.Name);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                </td>\r\n            </tr>\r\n            <tr>                \r" +
"\n                <td>\r\n                    <p style=\"margin-bottom:10px;\"><stron" +
"g>Fechas:</strong> ");


            
            #line 44 "..\..\Templates\AdvanceProgram.cshtml"
                                                                       Write(competition.StartDate.Value.ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral(" - ");


            
            #line 44 "..\..\Templates\AdvanceProgram.cshtml"
                                                                                                                          Write(competition.EndDate.Value.ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                </td>\r\n            </tr>            \r\n        </tbody>\r\n   " +
" </table>\r\n\r\n    <h2>Participantes</h2>\r\n    <hr style=\"margin:0 0 15px; height:" +
" 3px; color:#f74b4b; background:#f74b4b;\" />\r\n    <table border=\"0\">\r\n        <t" +
"body>\r\n");


            
            #line 54 "..\..\Templates\AdvanceProgram.cshtml"
             foreach (Enrollment enrollment in inscriptions)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>\r\n                        <p style=" +
"\"margin-bottom:10px;\">\r\n                            <strong>Jinete:</strong> ");


            
            #line 59 "..\..\Templates\AdvanceProgram.cshtml"
                                                Write(enrollment.Horse.Athlete.FullName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            - <strong>Caballo:</strong>\r\n                      " +
"      ");


            
            #line 61 "..\..\Templates\AdvanceProgram.cshtml"
                       Write(enrollment.Horse.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </p>\r\n                    </td>\r\n                </tr>\r" +
"\n");


            
            #line 65 "..\..\Templates\AdvanceProgram.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n    </table>\r\n\r\n    <h2>Miembros del jurado</h2>\r\n    <hr style" +
"=\"margin:0 0 15px; height: 3px; color:#f74b4b; background:#f74b4b;\" />\r\n    <tab" +
"le border=\"0\">\r\n        <tbody>\r\n");


            
            #line 73 "..\..\Templates\AdvanceProgram.cshtml"
             foreach (Seminary judge in seminary)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td><p style=\"margin-bottom:10px;\">");


            
            #line 76 "..\..\Templates\AdvanceProgram.cshtml"
                                                  Write(judge.Judge.FullName);

            
            #line default
            #line hidden
WriteLiteral("</p></td>\r\n                </tr>\r\n");


            
            #line 78 "..\..\Templates\AdvanceProgram.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n    </table>  \r\n</body>\r\n</html>");


        }
    }
}
#pragma warning restore 1591
