#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class _Templates_advanceProgram_cshtml : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        public override void Execute()
        {


WriteLiteral(@"

<!DOCTYPE html>
<html>
<head>
    <title>Contenido del concurso</title>
</head>
<body>
    <h2>Html List in PDF</h2>
    <table>
        <tr>
            <td>First Name</td>

            <td>Last Name</td>
        </tr>
    </table>
</body>
</html>");


        }
    }
}
#pragma warning restore 1591
